namespace StaticData.Cards
{
    public enum CardId
    {
        Bear = 0,
        Bee = 1,
        Camel = 2,
        Cat = 3,
        Chicken = 4,
        Cow = 5,
        Crab = 6,
        Crocodile = 7,
        Dog = 8,
        Dolphin = 9,
        Duck = 10,
        Elephant = 11,
        Fox = 12,
        Frog = 13,
        Giraffe = 14,
        Goat = 15,
        Horse = 16,
        Koala = 17,
        Ladybug = 18,
        Lion = 19,
        Monkey = 20,
        Octopus = 21,
        Owl = 22,
        Panda = 23,
        Penguin = 24,
        Pig = 25,
        Rabbit = 26,
        Rat = 27,
        Shark = 28,
        Sheep = 29,
        Snake = 30,
        Spider = 31,
        Starfish = 32,
        Tiger = 33,
        Turtle = 34,
        Zebra = 35,
    }
}